export interface APIEvent {
    id: string,
    description: string | null,
    awp: string,
    gdp: string,
    cause: string,
    severity: string,
    completed: boolean,
    confirmed: boolean,
    roadName: string,
    lastUpdatedTimestamp: number,
    current: boolean,
    latitude: number,
    longitude: number,
    teEventType: string,
    delay: string | null,
    returnToFreeFlow: unknown,
    creationDate: unknown,
    overallEndDate: number,
    overallStartDate: number,
    periods: {
        id: unknown,
        eventId: unknown,
        startPeriod: number,
        endPeriod: number
    }[],
    offSRN: boolean,
    eventReference: string,
    displayM6TollPromo: boolean,
    eventLanes: {
        laneName: string,
        laneStatus: string
    }[],
    laneClosureDescription: unknown,
    fullClosure: boolean,
    idProvidedBySource: number,
    linkIds: number[],
    additionalDescription: unknown,
    formatDesc: string[],
    gdpFormatted: string[],
    awpFormatted: string[],
    additionalDescriptionFormatted: string[],
    junction_ds_desc: string,
    junction_us_desc: string    
}